export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOAD_CURRENT_USER = 'LOAD_CURRENT_USER';
export const CLEAR_AUTH_PROCESS = 'CLEAR_AUTH_PROCESS';

export const USER_GET_ALL = 'USER_GET_ALL';
export const ARTICLES_GET_ALL = 'ARTICLES_GET_ALL';
export const TASKS_GET_ALL = 'TASKS_GET_ALL';
